require_relative '../setup'
require_relative './exercise_1'
require_relative './exercise_2'
require_relative './exercise_3'
require_relative './exercise_4'
require_relative './exercise_5'

puts "Exercise 6"
puts "----------"

# Your code goes here ...
@store4 = Store.find_by(id: 4)
@store5 = Store.find_by(id: 5)
@store6 = Store.find_by(id: 6)

@store1.employees.create(first_name: "Khurram", last_name: "Virani", hourly_rate: 60)
@store1.employees.create(first_name:"Emmit", last_name: "Beeden", hourly_rate: 77)
@store1.employees.create(first_name:"Jordana", last_name: "Adel", hourly_rate: 31)
@store1.employees.create(first_name:"Herminia", last_name: "Thorpe", hourly_rate: 75)
@store1.employees.create(first_name:"Reeta", last_name: "Hurst", hourly_rate: 21)
@store1.employees.create(first_name:"Ronni", last_name: "Kluger", hourly_rate: 45)
@store1.employees.create(first_name:"Erv", last_name: "Treneer", hourly_rate: 86)
@store1.employees.create(first_name:"Melissa", last_name: "Lecointe", hourly_rate: 58)
@store1.employees.create(first_name:"Hallie", last_name: "Dowber", hourly_rate: 65)
@store1.employees.create(first_name:"Eustacia", last_name: "Ervine", hourly_rate: 37)
@store1.employees.create(first_name:"Diarmid", last_name: "Castelletti", hourly_rate: 56)
@store1.employees.create(first_name:"Caitrin", last_name: "Enrrico", hourly_rate: 91)
@store1.employees.create(first_name:"Domeniga", last_name: "Finey", hourly_rate: 99)
@store1.employees.create(first_name:"Jozef", last_name: "Yacob", hourly_rate: 96)
@store1.employees.create(first_name:"Electra", last_name: "Charon", hourly_rate: 83)
@store1.employees.create(first_name:"Danna", last_name: "Woodger", hourly_rate: 55)
@store1.employees.create(first_name:"Matthus", last_name: "Bidewel", hourly_rate: 34)
@store2.employees.create(first_name:"Rey", last_name: "Clubley", hourly_rate: 58)
@store2.employees.create(first_name:"Terri-jo", last_name: "Rolfini", hourly_rate: 56)
@store2.employees.create(first_name:"Elise", last_name: "Birkhead", hourly_rate: 82)
@store2.employees.create(first_name:"Armand", last_name: "Lampart", hourly_rate: 77)
@store2.employees.create(first_name:"Rolph", last_name: "Melior", hourly_rate: 96)
@store2.employees.create(first_name:"Johnette", last_name: "Crayke", hourly_rate: 76)
@store2.employees.create(first_name:"Thorn", last_name: "Wherrit", hourly_rate: 96)
@store2.employees.create(first_name:"Salomo", last_name: "Langeren", hourly_rate: 59)
@store6.employees.create(first_name:"Angelita", last_name: "Egginton", hourly_rate: 46)
@store6.employees.create(first_name:"Ermengarde", last_name: "Hessle", hourly_rate: 28)
@store6.employees.create(first_name:"Salomi", last_name: "Llewhellin", hourly_rate: 64)
@store6.employees.create(first_name:"Ludovika", last_name: "Lanston", hourly_rate: 40)
@store6.employees.create(first_name:"Cullan", last_name: "Antonowicz", hourly_rate: 85)
@store6.employees.create(first_name:"Nicolette", last_name: "Mathy", hourly_rate: 44)
@store6.employees.create(first_name:"Clemmie", last_name: "Halsworth", hourly_rate: 34)
@store6.employees.create(first_name:"Suzy", last_name: "Abbis", hourly_rate: 29)
@store6.employees.create(first_name:"Mirna", last_name: "MacKenny", hourly_rate: 24)
@store2.employees.create(first_name:"Neil", last_name: "Siret", hourly_rate: 54)
@store2.employees.create(first_name:"Andie", last_name: "Berlin", hourly_rate: 65)
@store2.employees.create(first_name:"Byram", last_name: "Tredwell", hourly_rate: 41)
@store4.employees.create(first_name:"Kalli", last_name: "Abdee", hourly_rate: 54)
@store4.employees.create(first_name:"Earle", last_name: "Betonia", hourly_rate: 44)
@store4.employees.create(first_name:"Andrew", last_name: "Salzberg", hourly_rate: 69)
@store4.employees.create(first_name:"Cissiee", last_name: "Marie", hourly_rate: 98)
@store4.employees.create(first_name:"Cami", last_name: "Barras", hourly_rate: 50)
@store4.employees.create(first_name:"Henri", last_name: "Chalfont", hourly_rate: 94)
@store4.employees.create(first_name:"Imelda", last_name: "Musicka", hourly_rate: 55)
@store4.employees.create(first_name:"Florry", last_name: "Davidi", hourly_rate: 28)
@store4.employees.create(first_name:"Dimitry", last_name: "Chazotte", hourly_rate: 34)
@store5.employees.create(first_name:"Arabela", last_name: "Boich", hourly_rate: 91)
@store5.employees.create(first_name:"Ad", last_name: "Lucas", hourly_rate: 62)
@store5.employees.create(first_name:"Vivianne", last_name: "O'Hannen", hourly_rate: 83)
@store5.employees.create(first_name:"Lolly", last_name: "Moss", hourly_rate: 99)
@store5.employees.create(first_name:"Celestine", last_name: "Maffulli", hourly_rate: 28)
